OBJS = odb_main.o  odb_func.o

OBJS1 = odb_main.c

HEAD = odb_header.h

FUN = odb_func.c

C = gcc -c 

G = gcc -o

CL = *.o

O = odb

odb: $(OBJS) $(HEAD)
	$(G) $(O) $(OBJS)

odb_main.o: $(OBJS1) $(HEAD)
	$(C) $(OBJS1)

odb_func.o: $(FUN) $(HEAD)
	$(C) $(FUN)

clean:
	rm $(CL)
	














